
flowchart RL
 subgraph DeltaPhys["Платформа DeltaPhys"]
    direction TB
        UC1(["Перегляд публічної карти сесій"])
        UC2(["Реєстрація через email"])
        UC13(["Автентифікація"])
        UC3(["Перегляд деталей профілів"])
        UC4(["Спілкування в чатах"])
        UC5(["Створення виїздів та анкет"])
        UC6(["Подання заявок на участь"])
        UC7(["Верифікація особи"])
        UC8(["Створення комерційних виїздів"])
        UC9(["Перегляд розширеної статистики"])
        UC10(["Доступ до панелі керування"])
        UC11(["Блокування користувачів"])
        UC12(["Видалення сумнівних подій"])
  end
    UC1 --- G(("Гість"))
    UC2 --- G
    UC3 --- T(("Подорожуючий"))
    UC4 --- T
    UC5 --- T
    UC6 --- T
    UC8 --- O(("Організатор / Гід"))
    UC9 --- O
    UC10 --- Admin(("Адміністратор"))
    UC11 --- Admin
    UC12 --- Admin
    O -. успадковує .-> T
    T -. успадковує .-> G
    UC5 -. &lt;&gt; .-> UC13
    UC6 -. &lt;&gt; .-> UC13 & UC7